### ISSUE TITLE
'path' function not found

### ISSUE THREAD

**Issue by what-the-functor** [zwild/ammonite-term-repl#5]
When I run M-x ammonite-term-repl
There is an error `Symbol's function definition is void: path`

**Comment by kschwarz1116** [comment]
I too am encountering this. It appears to be coming from [here](https://github.com/zwild/ammonite-term-repl/blob/master/ammonite-term-repl.el#L172). Is there a missing dependency? I tried a google search looking for this function but couldn't find anything helpful. Doesn't look like it's in any of the common packages like `f`, `dash`, or `s`.

**Comment by kschwarz1116** [comment]
It looks like my earlier comment may have been a bit misleading. `path` is getting set in a handful of different `when-let` blocks, but it looks like it's getting used as a function somewhere that it shouldn't be (not sure where yet).

When I run `backtrace` from `org` mode trying to run an ammonite code block (using `ob-ammonite`), I get the following:
```
Debugger entered--Lisp error: (void-function path)
  path("~/.ammonite")
  ammonite-term-repl()
  org-babel-execute:amm("val a = 0\na" ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results . "replace") (:exports . "code") (:session . "none") (:cache . "no") (:noweb . "no") (:hlines . "no")$
  org-babel-execute-src-block(nil ("amm" "val a = 0\na" ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results . "replace") (:exports . "code") (:tangle . "no") (:hlines . "no") (:noweb . "no") ($
  org-ctrl-c-ctrl-c(nil)
  funcall-interactively(org-ctrl-c-ctrl-c nil)
  call-interactively(org-ctrl-c-ctrl-c nil nil)
  command-execute(org-ctrl-c-ctrl-c)
```

Still looking around in the file to figure out what's going on. My elisp-fu is not the best.

Judging from the first line of the trace though, it looks like the variable name `path` is getting applied to its value `"~/.ammonite"` somehow.

**Comment by suzzvv** [comment]
I'm sorry for not responsing immediately. Currently I don't have any spirit for this because my work. Sorry for that.

**Comment by kschwarz1116** [comment]
No worries about not responding! I submitted a PR, but in the meantime, I'm fine with just compiling it locally. It's up there now in case anyone else wants to use it. No rush!
